# Generated by Django 3.1.3 on 2024-01-24 18:03

from django.db import migrations
import djongo.models.fields
from core.models.mongo_models import LogAdditionalInfo

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='additional_info',
            field=djongo.models.fields.EmbeddedField(default=None, model_container=LogAdditionalInfo),
            preserve_default=False,
        ),
    ]
