# Generated by Django 3.1.3 on 2024-01-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_log_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
